name: "Pull Request Comment From File"
description: "A GitHub Action that comment on Pull Request with file path"
author: "Hirofumi Suzuki"
inputs:
  owner:
    description: "The owner name of repository on PR"
    required: true
  repo:
    description: "The repo name on PR"
    required: true
  pr_number:
    description: "The PR number"
    required: true
  filepath:
    description: "The file path with contents"
    required: true
  template:
    description: "The template of comment"
    required: false
outputs:
  url:
    description: "The comment url on PR"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "message-square"
  color: "green"
